[2025-07-07T10:07:24.414+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: master_etl.trigger_fact_sales_activity manual__2025-07-07T09:48:08.086116+00:00 [queued]>
[2025-07-07T10:07:24.465+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: master_etl.trigger_fact_sales_activity manual__2025-07-07T09:48:08.086116+00:00 [queued]>
[2025-07-07T10:07:24.466+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-07-07T10:07:24.568+0000] {taskinstance.py:1327} INFO - Executing <Task(TriggerDagRunOperator): trigger_fact_sales_activity> on 2025-07-07 09:48:08.086116+00:00
[2025-07-07T10:07:24.589+0000] {standard_task_runner.py:57} INFO - Started process 836 to run task
[2025-07-07T10:07:24.596+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'master_etl', 'trigger_fact_sales_activity', 'manual__2025-07-07T09:48:08.086116+00:00', '--job-id', '317', '--raw', '--subdir', 'DAGS_FOLDER/master_etl.py', '--cfg-path', '/tmp/tmpwmxsyap3']
[2025-07-07T10:07:24.597+0000] {standard_task_runner.py:85} INFO - Job 317: Subtask trigger_fact_sales_activity
[2025-07-07T10:07:24.824+0000] {task_command.py:410} INFO - Running <TaskInstance: master_etl.trigger_fact_sales_activity manual__2025-07-07T09:48:08.086116+00:00 [running]> on host 1622b3ff66d0
[2025-07-07T10:07:25.223+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='master_etl' AIRFLOW_CTX_TASK_ID='trigger_fact_sales_activity' AIRFLOW_CTX_EXECUTION_DATE='2025-07-07T09:48:08.086116+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-07T09:48:08.086116+00:00'
[2025-07-07T10:07:25.660+0000] {secrets_masker.py:278} WARNING - Unable to redact <TaskInstanceState.SUCCESS: 'success'>, please report this via <https://github.com/apache/airflow/issues>. Error was: TypeError: __call__() missing 1 required positional argument: 'value'
[2025-07-07T10:07:25.659+0000] {trigger_dagrun.py:201} INFO - Waiting for etl_fact_sales_activity on 2025-07-07T10:07:25.226369+00:00 to become allowed state [<TaskInstanceState.SUCCESS: 'success'>] ...
[2025-07-07T10:08:25.744+0000] {secrets_masker.py:278} WARNING - Unable to redact <TaskInstanceState.SUCCESS: 'success'>, please report this via <https://github.com/apache/airflow/issues>. Error was: TypeError: __call__() missing 1 required positional argument: 'value'
[2025-07-07T10:08:25.741+0000] {trigger_dagrun.py:201} INFO - Waiting for etl_fact_sales_activity on 2025-07-07T10:07:25.226369+00:00 to become allowed state [<TaskInstanceState.SUCCESS: 'success'>] ...
[2025-07-07T10:09:25.776+0000] {secrets_masker.py:278} WARNING - Unable to redact <TaskInstanceState.SUCCESS: 'success'>, please report this via <https://github.com/apache/airflow/issues>. Error was: TypeError: __call__() missing 1 required positional argument: 'value'
[2025-07-07T10:09:25.776+0000] {trigger_dagrun.py:201} INFO - Waiting for etl_fact_sales_activity on 2025-07-07T10:07:25.226369+00:00 to become allowed state [<TaskInstanceState.SUCCESS: 'success'>] ...
[2025-07-07T10:10:25.807+0000] {secrets_masker.py:278} WARNING - Unable to redact <TaskInstanceState.SUCCESS: 'success'>, please report this via <https://github.com/apache/airflow/issues>. Error was: TypeError: __call__() missing 1 required positional argument: 'value'
[2025-07-07T10:10:25.805+0000] {trigger_dagrun.py:201} INFO - Waiting for etl_fact_sales_activity on 2025-07-07T10:07:25.226369+00:00 to become allowed state [<TaskInstanceState.SUCCESS: 'success'>] ...
[2025-07-07T10:11:25.909+0000] {secrets_masker.py:278} WARNING - Unable to redact <TaskInstanceState.SUCCESS: 'success'>, please report this via <https://github.com/apache/airflow/issues>. Error was: TypeError: __call__() missing 1 required positional argument: 'value'
[2025-07-07T10:11:25.906+0000] {trigger_dagrun.py:201} INFO - Waiting for etl_fact_sales_activity on 2025-07-07T10:07:25.226369+00:00 to become allowed state [<TaskInstanceState.SUCCESS: 'success'>] ...
[2025-07-07T10:12:25.981+0000] {secrets_masker.py:278} WARNING - Unable to redact <TaskInstanceState.SUCCESS: 'success'>, please report this via <https://github.com/apache/airflow/issues>. Error was: TypeError: __call__() missing 1 required positional argument: 'value'
[2025-07-07T10:12:25.978+0000] {trigger_dagrun.py:201} INFO - Waiting for etl_fact_sales_activity on 2025-07-07T10:07:25.226369+00:00 to become allowed state [<TaskInstanceState.SUCCESS: 'success'>] ...
[2025-07-07T10:13:26.128+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/trigger_dagrun.py", line 208, in execute
    raise AirflowException(f"{self.trigger_dag_id} failed with failed states {state}")
airflow.exceptions.AirflowException: etl_fact_sales_activity failed with failed states failed
[2025-07-07T10:13:26.140+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=master_etl, task_id=trigger_fact_sales_activity, execution_date=20250707T094808, start_date=20250707T100724, end_date=20250707T101326
[2025-07-07T10:13:26.172+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 317 for task trigger_fact_sales_activity (etl_fact_sales_activity failed with failed states failed; 836)
[2025-07-07T10:13:26.184+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-07-07T10:13:26.302+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
