[2025-07-07T02:05:03.058+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_fact_claim.run_etl_fact_claim scheduled__2025-07-06T02:00:00+00:00 [queued]>
[2025-07-07T02:05:03.169+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_fact_claim.run_etl_fact_claim scheduled__2025-07-06T02:00:00+00:00 [queued]>
[2025-07-07T02:05:03.170+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2025-07-07T02:05:03.214+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): run_etl_fact_claim> on 2025-07-06 02:00:00+00:00
[2025-07-07T02:05:03.219+0000] {standard_task_runner.py:57} INFO - Started process 259 to run task
[2025-07-07T02:05:03.225+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_fact_claim', 'run_etl_fact_claim', 'scheduled__2025-07-06T02:00:00+00:00', '--job-id', '96', '--raw', '--subdir', 'DAGS_FOLDER/etl_fact_claim.py', '--cfg-path', '/tmp/tmp44muy58t']
[2025-07-07T02:05:03.232+0000] {standard_task_runner.py:85} INFO - Job 96: Subtask run_etl_fact_claim
[2025-07-07T02:05:03.672+0000] {task_command.py:410} INFO - Running <TaskInstance: etl_fact_claim.run_etl_fact_claim scheduled__2025-07-06T02:00:00+00:00 [running]> on host 1622b3ff66d0
[2025-07-07T02:05:04.110+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_fact_claim' AIRFLOW_CTX_TASK_ID='run_etl_fact_claim' AIRFLOW_CTX_EXECUTION_DATE='2025-07-06T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-06T02:00:00+00:00'
[2025-07-07T02:05:04.175+0000] {base.py:73} INFO - Using connection ID '***_insurance_bi' for task execution.
[2025-07-07T02:05:04.254+0000] {base.py:73} INFO - Using connection ID '***_insurance_dw' for task execution.
[2025-07-07T02:05:04.407+0000] {base.py:73} INFO - Using connection ID '***_insurance_dw' for task execution.
[2025-07-07T02:05:04.775+0000] {python.py:183} INFO - Done. Returned value was: No valid data to load after removing NULLs
[2025-07-07T02:05:05.016+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=etl_fact_claim, task_id=run_etl_fact_claim, execution_date=20250706T020000, start_date=20250707T020503, end_date=20250707T020505
[2025-07-07T02:05:05.097+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-07-07T02:05:05.180+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
