[2025-07-07T08:00:06.016+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: master_etl.trigger_fact_customer_service manual__2025-07-07T07:44:54.258586+00:00 [queued]>
[2025-07-07T08:00:06.041+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: master_etl.trigger_fact_customer_service manual__2025-07-07T07:44:54.258586+00:00 [queued]>
[2025-07-07T08:00:06.041+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-07-07T08:00:06.061+0000] {taskinstance.py:1327} INFO - Executing <Task(TriggerDagRunOperator): trigger_fact_customer_service> on 2025-07-07 07:44:54.258586+00:00
[2025-07-07T08:00:06.069+0000] {standard_task_runner.py:57} INFO - Started process 651 to run task
[2025-07-07T08:00:06.077+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'master_etl', 'trigger_fact_customer_service', 'manual__2025-07-07T07:44:54.258586+00:00', '--job-id', '245', '--raw', '--subdir', 'DAGS_FOLDER/master_etl.py', '--cfg-path', '/tmp/tmpyhkqycw1']
[2025-07-07T08:00:06.079+0000] {standard_task_runner.py:85} INFO - Job 245: Subtask trigger_fact_customer_service
[2025-07-07T08:00:06.167+0000] {task_command.py:410} INFO - Running <TaskInstance: master_etl.trigger_fact_customer_service manual__2025-07-07T07:44:54.258586+00:00 [running]> on host 1622b3ff66d0
[2025-07-07T08:00:06.287+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='master_etl' AIRFLOW_CTX_TASK_ID='trigger_fact_customer_service' AIRFLOW_CTX_EXECUTION_DATE='2025-07-07T07:44:54.258586+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-07T07:44:54.258586+00:00'
[2025-07-07T08:00:06.452+0000] {secrets_masker.py:278} WARNING - Unable to redact <TaskInstanceState.SUCCESS: 'success'>, please report this via <https://github.com/apache/airflow/issues>. Error was: TypeError: __call__() missing 1 required positional argument: 'value'
[2025-07-07T08:00:06.451+0000] {trigger_dagrun.py:201} INFO - Waiting for etl_fact_customer_service on 2025-07-07T08:00:06.287916+00:00 to become allowed state [<TaskInstanceState.SUCCESS: 'success'>] ...
[2025-07-07T08:01:06.631+0000] {secrets_masker.py:278} WARNING - Unable to redact <TaskInstanceState.SUCCESS: 'success'>, please report this via <https://github.com/apache/airflow/issues>. Error was: TypeError: __call__() missing 1 required positional argument: 'value'
[2025-07-07T08:01:06.627+0000] {trigger_dagrun.py:201} INFO - Waiting for etl_fact_customer_service on 2025-07-07T08:00:06.287916+00:00 to become allowed state [<TaskInstanceState.SUCCESS: 'success'>] ...
[2025-07-07T08:02:06.721+0000] {trigger_dagrun.py:210} INFO - etl_fact_customer_service finished with allowed state success
[2025-07-07T08:02:06.749+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=master_etl, task_id=trigger_fact_customer_service, execution_date=20250707T074454, start_date=20250707T080006, end_date=20250707T080206
[2025-07-07T08:02:06.829+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-07-07T08:02:06.893+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
