[2025-07-07T03:14:45.329+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_fact_claim.run_etl_fact_claim manual__2025-07-07T03:14:43.777389+00:00 [queued]>
[2025-07-07T03:14:45.349+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_fact_claim.run_etl_fact_claim manual__2025-07-07T03:14:43.777389+00:00 [queued]>
[2025-07-07T03:14:45.350+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-07-07T03:14:45.373+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): run_etl_fact_claim> on 2025-07-07 03:14:43.777389+00:00
[2025-07-07T03:14:45.381+0000] {standard_task_runner.py:57} INFO - Started process 365 to run task
[2025-07-07T03:14:45.386+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_fact_claim', 'run_etl_fact_claim', 'manual__2025-07-07T03:14:43.777389+00:00', '--job-id', '139', '--raw', '--subdir', 'DAGS_FOLDER/etl_fact_claim.py', '--cfg-path', '/tmp/tmp2yeebjq9']
[2025-07-07T03:14:45.391+0000] {standard_task_runner.py:85} INFO - Job 139: Subtask run_etl_fact_claim
[2025-07-07T03:14:45.476+0000] {task_command.py:410} INFO - Running <TaskInstance: etl_fact_claim.run_etl_fact_claim manual__2025-07-07T03:14:43.777389+00:00 [running]> on host 1622b3ff66d0
[2025-07-07T03:14:45.590+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_fact_claim' AIRFLOW_CTX_TASK_ID='run_etl_fact_claim' AIRFLOW_CTX_EXECUTION_DATE='2025-07-07T03:14:43.777389+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-07T03:14:43.777389+00:00'
[2025-07-07T03:14:45.623+0000] {base.py:73} INFO - Using connection ID '***_insurance_bi' for task execution.
[2025-07-07T03:14:45.748+0000] {base.py:73} INFO - Using connection ID '***_insurance_dw' for task execution.
[2025-07-07T03:14:45.801+0000] {base.py:73} INFO - Using connection ID '***_insurance_dw' for task execution.
[2025-07-07T03:14:46.174+0000] {python.py:183} INFO - Done. Returned value was: No valid data to load after removing NULLs
[2025-07-07T03:14:46.210+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=etl_fact_claim, task_id=run_etl_fact_claim, execution_date=20250707T031443, start_date=20250707T031445, end_date=20250707T031446
[2025-07-07T03:14:46.264+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-07-07T03:14:46.288+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
