[2025-07-07T08:14:38.954+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: master_etl.trigger_dim_customer manual__2025-07-07T08:13:32.189909+00:00 [queued]>
[2025-07-07T08:14:38.976+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: master_etl.trigger_dim_customer manual__2025-07-07T08:13:32.189909+00:00 [queued]>
[2025-07-07T08:14:38.977+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-07-07T08:14:39.003+0000] {taskinstance.py:1327} INFO - Executing <Task(TriggerDagRunOperator): trigger_dim_customer> on 2025-07-07 08:13:32.189909+00:00
[2025-07-07T08:14:39.009+0000] {standard_task_runner.py:57} INFO - Started process 720 to run task
[2025-07-07T08:14:39.020+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'master_etl', 'trigger_dim_customer', 'manual__2025-07-07T08:13:32.189909+00:00', '--job-id', '274', '--raw', '--subdir', 'DAGS_FOLDER/master_etl.py', '--cfg-path', '/tmp/tmp1py0fs5o']
[2025-07-07T08:14:39.021+0000] {standard_task_runner.py:85} INFO - Job 274: Subtask trigger_dim_customer
[2025-07-07T08:14:39.126+0000] {task_command.py:410} INFO - Running <TaskInstance: master_etl.trigger_dim_customer manual__2025-07-07T08:13:32.189909+00:00 [running]> on host 1622b3ff66d0
[2025-07-07T08:14:39.236+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='master_etl' AIRFLOW_CTX_TASK_ID='trigger_dim_customer' AIRFLOW_CTX_EXECUTION_DATE='2025-07-07T08:13:32.189909+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-07T08:13:32.189909+00:00'
[2025-07-07T08:14:39.439+0000] {secrets_masker.py:278} WARNING - Unable to redact <TaskInstanceState.SUCCESS: 'success'>, please report this via <https://github.com/apache/airflow/issues>. Error was: TypeError: __call__() missing 1 required positional argument: 'value'
[2025-07-07T08:14:39.438+0000] {trigger_dagrun.py:201} INFO - Waiting for etl_dim_customer on 2025-07-07T08:14:39.237532+00:00 to become allowed state [<TaskInstanceState.SUCCESS: 'success'>] ...
[2025-07-07T08:15:39.565+0000] {secrets_masker.py:278} WARNING - Unable to redact <TaskInstanceState.SUCCESS: 'success'>, please report this via <https://github.com/apache/airflow/issues>. Error was: TypeError: __call__() missing 1 required positional argument: 'value'
[2025-07-07T08:15:39.561+0000] {trigger_dagrun.py:201} INFO - Waiting for etl_dim_customer on 2025-07-07T08:14:39.237532+00:00 to become allowed state [<TaskInstanceState.SUCCESS: 'success'>] ...
[2025-07-07T08:16:39.652+0000] {secrets_masker.py:278} WARNING - Unable to redact <TaskInstanceState.SUCCESS: 'success'>, please report this via <https://github.com/apache/airflow/issues>. Error was: TypeError: __call__() missing 1 required positional argument: 'value'
[2025-07-07T08:16:39.651+0000] {trigger_dagrun.py:201} INFO - Waiting for etl_dim_customer on 2025-07-07T08:14:39.237532+00:00 to become allowed state [<TaskInstanceState.SUCCESS: 'success'>] ...
[2025-07-07T08:17:39.752+0000] {secrets_masker.py:278} WARNING - Unable to redact <TaskInstanceState.SUCCESS: 'success'>, please report this via <https://github.com/apache/airflow/issues>. Error was: TypeError: __call__() missing 1 required positional argument: 'value'
[2025-07-07T08:17:39.751+0000] {trigger_dagrun.py:201} INFO - Waiting for etl_dim_customer on 2025-07-07T08:14:39.237532+00:00 to become allowed state [<TaskInstanceState.SUCCESS: 'success'>] ...
[2025-07-07T08:18:39.841+0000] {secrets_masker.py:278} WARNING - Unable to redact <TaskInstanceState.SUCCESS: 'success'>, please report this via <https://github.com/apache/airflow/issues>. Error was: TypeError: __call__() missing 1 required positional argument: 'value'
[2025-07-07T08:18:39.840+0000] {trigger_dagrun.py:201} INFO - Waiting for etl_dim_customer on 2025-07-07T08:14:39.237532+00:00 to become allowed state [<TaskInstanceState.SUCCESS: 'success'>] ...
[2025-07-07T08:19:39.926+0000] {secrets_masker.py:278} WARNING - Unable to redact <TaskInstanceState.SUCCESS: 'success'>, please report this via <https://github.com/apache/airflow/issues>. Error was: TypeError: __call__() missing 1 required positional argument: 'value'
[2025-07-07T08:19:39.925+0000] {trigger_dagrun.py:201} INFO - Waiting for etl_dim_customer on 2025-07-07T08:14:39.237532+00:00 to become allowed state [<TaskInstanceState.SUCCESS: 'success'>] ...
[2025-07-07T08:20:40.019+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/trigger_dagrun.py", line 208, in execute
    raise AirflowException(f"{self.trigger_dag_id} failed with failed states {state}")
airflow.exceptions.AirflowException: etl_dim_customer failed with failed states failed
[2025-07-07T08:20:40.028+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=master_etl, task_id=trigger_dim_customer, execution_date=20250707T081332, start_date=20250707T081438, end_date=20250707T082040
[2025-07-07T08:20:40.049+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 274 for task trigger_dim_customer (etl_dim_customer failed with failed states failed; 720)
[2025-07-07T08:20:40.084+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-07-07T08:20:40.130+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
